#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 11, 2018 09:18:41 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    gui_support.set_Tk_var()
    top = Hyperelastic_curve_fit (root)
    gui_support.init(root, top)
    root.mainloop()

w = None
def create_Hyperelastic_curve_fit(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    gui_support.set_Tk_var()
    top = Hyperelastic_curve_fit (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Hyperelastic_curve_fit():
    global w
    w.destroy()
    w = None


class Hyperelastic_curve_fit:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("510x555+624+268")
        top.title("Hyperelastic curve fit")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.EntryFilename = Entry(top)
        self.EntryFilename.place(relx=0.2, rely=0.04,height=24, relwidth=0.4)
        self.EntryFilename.configure(background="white")
        self.EntryFilename.configure(disabledforeground="#a3a3a3")
        self.EntryFilename.configure(font="TkFixedFont")
        self.EntryFilename.configure(foreground="#000000")
        self.EntryFilename.configure(highlightbackground="#d9d9d9")
        self.EntryFilename.configure(highlightcolor="black")
        self.EntryFilename.configure(insertbackground="black")
        self.EntryFilename.configure(selectbackground="#c4c4c4")
        self.EntryFilename.configure(selectforeground="black")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.04, rely=0.04, height=26, width=69)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Filename:''')

        self.ButtonProcess = Button(top)
        self.ButtonProcess.place(relx=0.04, rely=0.22, height=26, width=470)
        self.ButtonProcess.configure(activebackground="#d9d9d9")
        self.ButtonProcess.configure(activeforeground="#000000")
        self.ButtonProcess.configure(background="#d9d9d9")
        self.ButtonProcess.configure(command=gui_support.ButtonProcess_Click)
        self.ButtonProcess.configure(disabledforeground="#a3a3a3")
        self.ButtonProcess.configure(foreground="#000000")
        self.ButtonProcess.configure(highlightbackground="#d9d9d9")
        self.ButtonProcess.configure(highlightcolor="black")
        self.ButtonProcess.configure(pady="0")
        self.ButtonProcess.configure(text='''Process File''')

        self.FramePlot = Frame(top)
        self.FramePlot.place(relx=0.04, rely=0.52, relheight=0.37, relwidth=0.92)

        self.FramePlot.configure(relief=GROOVE)
        self.FramePlot.configure(borderwidth="2")
        self.FramePlot.configure(relief=GROOVE)
        self.FramePlot.configure(background="#d9d9d9")
        self.FramePlot.configure(highlightbackground="#d9d9d9")
        self.FramePlot.configure(highlightcolor="black")
        self.FramePlot.configure(width=465)

        self.EntrySamples = Entry(top)
        self.EntrySamples.place(relx=0.2, rely=0.09,height=24, relwidth=0.4)
        self.EntrySamples.configure(background="white")
        self.EntrySamples.configure(disabledforeground="#a3a3a3")
        self.EntrySamples.configure(font="TkFixedFont")
        self.EntrySamples.configure(foreground="#000000")
        self.EntrySamples.configure(highlightbackground="#d9d9d9")
        self.EntrySamples.configure(highlightcolor="black")
        self.EntrySamples.configure(insertbackground="black")
        self.EntrySamples.configure(selectbackground="#c4c4c4")
        self.EntrySamples.configure(selectforeground="black")

        self.Label2 = Label(top)
        self.Label2.place(relx=0.04, rely=0.09, height=26, width=65)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Samples:''')

        self.FrameNavigation = Frame(top)
        self.FrameNavigation.place(relx=0.04, rely=0.9, relheight=0.06
                , relwidth=0.92)
        self.FrameNavigation.configure(relief=GROOVE)
        self.FrameNavigation.configure(borderwidth="2")
        self.FrameNavigation.configure(relief=GROOVE)
        self.FrameNavigation.configure(background="#d9d9d9")
        self.FrameNavigation.configure(highlightbackground="#d9d9d9")
        self.FrameNavigation.configure(highlightcolor="black")
        self.FrameNavigation.configure(width=465)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.04, rely=0.14, height=26, width=71)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Delimiter:''')

        self.EntryDelimiter = Entry(top)
        self.EntryDelimiter.place(relx=0.2, rely=0.14,height=24, relwidth=0.4)
        self.EntryDelimiter.configure(background="white")
        self.EntryDelimiter.configure(disabledforeground="#a3a3a3")
        self.EntryDelimiter.configure(font="TkFixedFont")
        self.EntryDelimiter.configure(foreground="#000000")
        self.EntryDelimiter.configure(highlightbackground="#d9d9d9")
        self.EntryDelimiter.configure(highlightcolor="black")
        self.EntryDelimiter.configure(insertbackground="black")
        self.EntryDelimiter.configure(selectbackground="#c4c4c4")
        self.EntryDelimiter.configure(selectforeground="black")

        self.RadiobuttonUT = Radiobutton(top)
        self.RadiobuttonUT.place(relx=0.04, rely=0.29, relheight=0.04
                , relwidth=0.04)
        self.RadiobuttonUT.configure(activebackground="#d9d9d9")
        self.RadiobuttonUT.configure(activeforeground="#000000")
        self.RadiobuttonUT.configure(background="#d9d9d9")
        self.RadiobuttonUT.configure(disabledforeground="#a3a3a3")
        self.RadiobuttonUT.configure(foreground="#000000")
        self.RadiobuttonUT.configure(highlightbackground="#d9d9d9")
        self.RadiobuttonUT.configure(highlightcolor="black")
        self.RadiobuttonUT.configure(justify=LEFT)
        self.RadiobuttonUT.configure(value="0")
        self.RadiobuttonUT.configure(variable=gui_support.radiovar)
        self.RadiobuttonUT.configure(width=169)

        self.RadiobuttonET = Radiobutton(top)
        self.RadiobuttonET.place(relx=0.04, rely=0.34, relheight=0.04
                , relwidth=0.04)
        self.RadiobuttonET.configure(activebackground="#d9d9d9")
        self.RadiobuttonET.configure(activeforeground="#000000")
        self.RadiobuttonET.configure(background="#d9d9d9")
        self.RadiobuttonET.configure(disabledforeground="#a3a3a3")
        self.RadiobuttonET.configure(foreground="#000000")
        self.RadiobuttonET.configure(highlightbackground="#d9d9d9")
        self.RadiobuttonET.configure(highlightcolor="black")
        self.RadiobuttonET.configure(justify=LEFT)
        self.RadiobuttonET.configure(value="1")
        self.RadiobuttonET.configure(variable=gui_support.radiovar)

        self.RadiobuttonPS = Radiobutton(top)
        self.RadiobuttonPS.place(relx=0.04, rely=0.4, relheight=0.04
                , relwidth=0.04)
        self.RadiobuttonPS.configure(activebackground="#d9d9d9")
        self.RadiobuttonPS.configure(activeforeground="#000000")
        self.RadiobuttonPS.configure(background="#d9d9d9")
        self.RadiobuttonPS.configure(disabledforeground="#a3a3a3")
        self.RadiobuttonPS.configure(foreground="#000000")
        self.RadiobuttonPS.configure(highlightbackground="#d9d9d9")
        self.RadiobuttonPS.configure(highlightcolor="black")
        self.RadiobuttonPS.configure(justify=LEFT)
        self.RadiobuttonPS.configure(value="2")
        self.RadiobuttonPS.configure(variable=gui_support.radiovar)

        self.Label4 = Label(top)
        self.Label4.place(relx=0.08, rely=0.28, height=26, width=111)
        self.Label4.configure(anchor=W)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Uniaxial tension''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.08, rely=0.33, height=26, width=131)
        self.Label5.configure(anchor=W)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Equibiaxial tension''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.08, rely=0.39, height=26, width=74)
        self.Label6.configure(anchor=W)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Pure shear''')

        self.ButtonFitModel = Button(top)
        self.ButtonFitModel.place(relx=0.04, rely=0.45, height=26, width=470)
        self.ButtonFitModel.configure(activebackground="#d9d9d9")
        self.ButtonFitModel.configure(activeforeground="#000000")
        self.ButtonFitModel.configure(background="#d9d9d9")
        self.ButtonFitModel.configure(command=gui_support.ButtonFitModel_Click)
        self.ButtonFitModel.configure(disabledforeground="#a3a3a3")
        self.ButtonFitModel.configure(foreground="#000000")
        self.ButtonFitModel.configure(highlightbackground="#d9d9d9")
        self.ButtonFitModel.configure(highlightcolor="black")
        self.ButtonFitModel.configure(pady="0")
        self.ButtonFitModel.configure(text='''Fit model''')






if __name__ == '__main__':
    vp_start_gui()



